services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: stepwise-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - IMPORT_TOKEN=stepwize_test
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - stepwise-network

  callback:
    build:
      context: ./interface
      dockerfile: Dockerfile
    container_name: stepwise-interface
    ports:
      - "4000:4000"
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - stepwise-network

networks:
  stepwise-network:
    driver: bridge
